### PR TITLE
add filesize

### PR DESCRIPTION
**Pull request by antonmes**
tested with regular file & symlink 

can we add tests here?

### CODE REVIEW

**Comment by Danappelxx** [comment]
Tests would be a good idea. Just need to port some of [these](https://github.com/sustrik/libmill/tree/master/tests) over (looks like its just `assert` tests - nothing fancy). However, since libvenice differs from libmill in some ways, we should have @paulofaria do it :stuck_out_tongue:.

**Comment by paulofaria** [comment]
Yeah we should have tests! but I'm considering something else. Martin (libmill author) is working on libdill:

http://libdill.org/

Libdill would be much better to wrap cause it uses idiomatic C. The main reason we need a fork from libmill is because libmill uses a lot of C macros which don't translate to swift. The other reason is that we store values in the channel buffer in Swiftland so I modified libmill to remove the value storage from the channels. This difference would still exist on libdill, but maybe we can influence libdill so we don't have to fork at all. This would be a huge win for us.

**Comment by antonmes** [comment]
fixed.

**Comment by antonmes** [comment]
@paulofaria

**Comment by antonmes** [comment]
oh, i should move it to CLibvenice now (@paulo)

**Comment by paulofaria** [comment]
@antonmes yeah!

**Pull request merged**
